# Generated by Django 4.2.30 on 2026-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('airtel_money', 'Airtel Money'), ('card', 'Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Customer-provided transaction reference', max_length=100),
        ),
    ]
