# Generated by Django 4.2.30 on 2026-09-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_payment_provider_alter_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jerseyvariant',
            name='sku',
        ),
    ]
