# Generated by Django 4.2.30 on 2026-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_jerseyvariant_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['category', 'league', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('clubs', 'Clubs'), ('nations', 'Nations'), ('vintage', 'Vintage'), ('special', 'Special')], default='clubs', help_text='Controls which nav dropdown this appears under.', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
