# Generated by Django 4.2.30 on 2026-09-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_team_options_team_category_team_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='kind',
            field=models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('third', 'Third'), ('gk', 'Goalkeeper'), ('retro', 'Retro'), ('vintage', 'vintage')], default='home', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('clubs', 'Clubs'), ('nations', 'Nations'), ('special', 'Special')], default='clubs', help_text='Controls which nav dropdown this appears under.', max_length=20),
        ),
    ]
