# Generated by Django 4.2.30 on 2026-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_jersey_kind_alter_team_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='kind',
            field=models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('third', 'Third'), ('gk', 'Goalkeeper'), ('retro', 'Retro'), ('vintage', 'Vintage')], default='home', max_length=10),
        ),
    ]
