# Generated by Django 4.2.30 on 2026-09-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_jersey_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash_on_delivery', 'Cash on Delivery'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('card', 'Card')], max_length=20),
        ),
    ]
